trigger:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: self
  - repository: AzureTemplates            # ID used to reference pipeline templates below
    type: git
    name: azure-templates

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'project'
  containerRegistry: 'LCAcollect ACR'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Helm registry
  azureSubscriptionForACR: 'LCAcollect Shared Container Reg'
  azureResourceGroupForACR: 'molio-lcacollect-Shared-container-reg-rg'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  workingDirectory: $(System.DefaultWorkingDirectory)

  # Variables
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
- stage: Test
  displayName: Run tests
  jobs:
    - template: pipelines/python-test.yaml@AzureTemplates
      parameters:
        vmImageName: $(vmImageName)
        workingDirectory: $(workingDirectory)

- stage: Artifact
  displayName: Publish GraphQL Schema
  condition: and(succeeded(), and(eq(variables.isMain, 'true'), eq(variables.isPR, 'false')))
  dependsOn: Test
  jobs:
    - job: PublishSchema
      displayName: Publish GraphQL Schema
      steps:
      - publish: $(workingDirectory)/graphql/schema.graphql
        artifact: project.graphql

- stage: Deploy
  displayName: Build and Deploy
  condition: and(succeeded(), and(eq(variables.isMain, 'true'), eq(variables.isPR, 'false')))
  dependsOn: 
    - Test
    - Artifact
  jobs:
    - template: pipelines/docker-build.yaml@AzureTemplates
      parameters:
        vmImageName: $(vmImageName)
        dockerfilePath: $(dockerfilePath)
        imageRepository: $(imageRepository)
        containerRegistry: $(containerRegistry)
        tag: $(tag)
    - template: pipelines/helm-deploy.yaml@AzureTemplates
      parameters:
        vmImageName: $(vmImageName)
        azureSubscription: $(azureSubscriptionForACR)
        containerRegistry: $(containerRegistry)
        chartName: $(imageRepository)
        tag: $(tag)
        workingDirectory: $(workingDirectory)/helm