[tool.pytest.ini_options]
#addopts = "--cov=src --cov-report=term-missing --cov-branch --cov-report=xml"
asyncio_mode = "auto"
console_output_style = "count"
pythonpath = "src"
required_plugins = ["pytest-cov>=4.0.0", "pytest-azurepipelines"]
testpaths = ["tests/"]

env = [
    "SERVER_NAME=LCA Test",
    "SERVER_HOST=http://test.com",
    "PROJECT_NAME=LCA Test",
    "POSTGRES_HOST=localhost",
    "POSTGRES_USER=postgresuser",
    "POSTGRES_PASSWORD=mypassword",
    "POSTGRES_DB=project",
    "POSTGRES_PORT=5632",
    "AAD_OPENAPI_CLIENT_ID=b7fc0d3e-fdd9-4260-8b01-12cad623c64a",
    "AAD_APP_CLIENT_ID=40c35f10-9d17-43dc-bf6c-6208945c98c6",
    "AAD_TENANT_ID=11be1538-79d8-4939-82b8-b767805d825b",
    "AAD_TEST_CLIENT_SECRET=RmQ7Q~ejj0xaB566qjekYB6Oivq06Sk4Q69Hw",
    "AAD_GRAPH_SECRET=PLACEHOLDER",
    "SENDGRID_SECRET=PLACEHOLDER",
    "ROUTER_URL=http://router.url",
    "STORAGE_ACCOUNT_URL=https://documentationbundle.blob.core.windows.net/",
    "STORAGE_CONTAINER_NAME=PLACEHOLDER",
    "STORAGE_ACCESS_KEY=PLACEHOLDER",
    "STORAGE_BASE_PATH=test",
    "EMAIL_NOTIFICATION_FROM=no-reply@arkitema.com",
    "INTERNAL_EMAIL_DOMAIN_NAMES=arkitema,cowi,cowicloud",
    "DEFAULT_AD_FQDN=cowi.onmicrosoft.com"

]

[tool.coverage.run]
omit=["src/initial_data/*.py", "src/exceptions/*.py", "src/initialize.py", "src/schema/*.py"]

[tool.black]
line-length = 120
target-version = ['py310']
extend-include = """
^/alembic
"""

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
