[tool.pytest.ini_options]
#addopts = "--cov=src --cov-report=term-missing --cov-branch --cov-report=xml"
asyncio_mode = "auto"
console_output_style = "count"
pythonpath = "src"
required_plugins = ["pytest-cov>=4.0.0"]
testpaths = ["tests/"]

env = [
    "SERVER_NAME=LCA Test",
    "SERVER_HOST=http://test.com",
    "PROJECT_NAME=LCA Test",
    "POSTGRES_HOST=localhost",
    "POSTGRES_USER=postgresuser",
    "POSTGRES_PASSWORD=mypassword",
    "POSTGRES_DB=project",
    "POSTGRES_PORT=5632",
    "AAD_OPENAPI_CLIENT_ID=PLACEHOLDER",
    "AAD_APP_CLIENT_ID=PLACEHOLDER",
    "AAD_TENANT_ID=PLACEHOLDER",
    "AAD_TEST_CLIENT_SECRET=PLACEHOLDER",
    "AAD_GRAPH_SECRET=PLACEHOLDER",
    "SENDGRID_SECRET=PLACEHOLDER",
    "ROUTER_URL=http://router.url",
    "STORAGE_ACCOUNT_URL=PLACEHOLDER",
    "STORAGE_CONTAINER_NAME=PLACEHOLDER",
    "STORAGE_ACCESS_KEY=PLACEHOLDER",
    "STORAGE_BASE_PATH=test",
    "EMAIL_NOTIFICATION_FROM=no-reply@arkitema.com",
    "INTERNAL_EMAIL_DOMAIN_NAMES=arkitema,cowi,cowicloud",
    "DEFAULT_AD_FQDN=cowi.onmicrosoft.com"

]

[tool.coverage.run]
omit=["src/initial_data/*.py", "src/exceptions/*.py", "src/initialize.py", "src/schema/*.py"]

[tool.black]
line-length = 120
target-version = ['py310']
extend-include = """
^/alembic
"""

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
