{{- if eq .Values.deployType "DEV" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  password: 'YWRnYWtqMjM1NGpoc2tsaDc4MzU0'
  username: 'cG9zdGdyZXN1c2Vy' #postgresuser
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.aadGraphSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  secret: {{ .Values.backend.aadGraphSecret.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.storageAccountURL.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  secret: {{ .Values.backend.storageAccountURL.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.storageContainer.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  secret: {{ .Values.backend.storageContainer.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.storageSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  secret: {{ .Values.backend.storageSecret.value }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.emailSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  secret: {{ .Values.backend.emailSecret.value }}
---
{{- else if eq .Values.deployType "PROD"}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretStore.userAssignedIdentityID }}
    tenantID: {{ .Values.secretStore.tenantId }}
    keyvaultName: {{ .Values.secretStore.name }}
    objects: |
      array:
        - |
          objectName: {{ .Values.db.username }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.db.secret }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.backend.aadGraphSecret.name }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.backend.emailSecret.name }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{.Values.backend.storageAccountURL.name }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.backend.storageContainer.name }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.backend.storageSecret.name }}
          objectType: secret
          objectVersion: ""
  secretObjects:
    - data:
      - key: username
        objectName: {{ .Values.db.username }}
      - key: password
        objectName: {{ .Values.db.secret }}
      secretName: {{ .Values.db.secret }}
      type: generic
    - data:
        - key: secret
          objectName: {{ .Values.backend.emailSecret.name }}
      secretName: {{ .Values.backend.emailSecret.name }}
      type: generic
    - data:
        - key: secret
          objectName: {{ .Values.backend.aadGraphSecret.name }}
      secretName: {{ .Values.backend.aadGraphSecret.name }}
      type: generic
    - data:
        - key: secret
          objectName: {{.Values.backend.storageAccountURL.name }}
      secretName: {{.Values.backend.storageAccountURL.name }}
      type: generic
    - data:
        - key: secret
          objectName: {{ .Values.backend.storageContainer.name }}
      secretName: {{ .Values.backend.storageContainer.name }}
      type: generic
    - data:
        - key: secret
          objectName: {{ .Values.backend.storageSecret.name }}
      secretName: {{ .Values.backend.storageSecret.name }}
      type: generic
# Sources:
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#validate-the-secrets
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
{{- end }}