"""empty message

Revision ID: 39e7daea99ba
Revises: 7a7b62a85766
Create Date: 2022-10-11 14:52:59.776252

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "39e7daea99ba"
down_revision = "7a7b62a85766"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("projectmember_unique_constr", "projectmember", ["id"])
    op.add_column(
        "projectgroup",
        sa.Column("lead_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_index("ix_projectgroup_id", table_name="projectgroup")
    op.create_index(op.f("ix_projectgroup_id"), "projectgroup", ["id"], unique=True)
    op.create_foreign_key("fk_projectgroup", "projectgroup", "projectmember", ["lead_id"], ["id"])
    op.drop_column("projectmember", "project_group")
    op.create_table(
        "membergrouplink",
        sa.Column("member_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("group_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["projectgroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["projectmember.id"],
        ),
        sa.PrimaryKeyConstraint("member_id", "group_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("membergrouplink")
    op.add_column(
        "projectmember",
        sa.Column("project_group", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("projectmember_unique_constr", "projectmember", type_="unique")
    op.drop_constraint("fk_projectgroup", "projectgroup", type_="foreignkey")
    op.drop_index(op.f("ix_projectgroup_id"), table_name="projectgroup")
    op.create_index("ix_projectgroup_id", "projectgroup", ["id"], unique=False)
    op.drop_column("projectgroup", "lead_id")
    # ### end Alembic commands ###
