"""empty message

Revision ID: 7a7b62a85766
Revises: c602aa29ba9e
Create Date: 2022-09-22 16:52:24.194990

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a7b62a85766"
down_revision = "c602aa29ba9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projectmember", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index("ix_projectmember_email", table_name="projectmember")
    op.drop_constraint("projectmember_origin_id_fkey", "projectmember", type_="foreignkey")
    op.drop_column("projectmember", "email")
    op.drop_column("projectmember", "company")
    op.drop_column("projectmember", "name")
    op.drop_column("projectmember", "last_login")
    op.drop_column("projectmember", "origin_id")
    op.drop_column("projectmember", "role")
    op.alter_column("projectstage", "stage_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index("ix_member_email", table_name="member")
    op.drop_table("member")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_login", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="member_pkey"),
    )
    op.alter_column("projectstage", "stage_id", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("projectmember", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("projectmember", sa.Column("origin_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("projectmember", sa.Column("last_login", sa.DATE(), autoincrement=False, nullable=True))
    op.add_column("projectmember", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("projectmember", sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("projectmember", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key("projectmember_origin_id_fkey", "projectmember", "member", ["origin_id"], ["id"])
    op.create_index("ix_projectmember_email", "projectmember", ["email"], unique=False)
    op.drop_column("projectmember", "user_id")

    op.create_index("ix_member_email", "member", ["email"], unique=False)
    # ### end Alembic commands ###
