"""empty message

Revision ID: ee61906c1705
Revises: 39e7daea99ba
Create Date: 2022-11-16 10:05:59.898126

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee61906c1705"
down_revision = "39e7daea99ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "image_url")
    # ### end Alembic commands ###
