name: Container CI/CD Workflow

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage
  workflow_dispatch:

env:
  NAME: "project"
  TAG: ${{ github.run_number }}${{ github.ref-name != 'main' && '-dev' || ''}}

jobs:
  test:
    uses: lcacollect/.github/.github/workflows/test-python.yaml@main
  publish-schema:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-graphql.yaml@main
    needs: test
  build-container:
    uses: lcacollect/.github/.github/workflows/build-image.yaml@main
    needs: test
    with:
      tag: ${{ env.TAG }}
      registry: "lcacollect"
      name: ${{ env.NAME }}
  publish-chart:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-chart.yaml@main
    needs:
      - test
      - build-container
    with:
      tag: ${{ env.TAG }}
      registry: "lcacollect"
      name: ${{ env.NAME }}