name: Container CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test:
    uses: lcacollect/.github/.github/workflows/test-python.yaml@main
  publish-schema:
    needs: test
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-graphql.yaml@main
  build-container:
    uses: lcacollect/.github/.github/workflows/build-image.yaml@main
    needs: test
    with:
      tag: ${{ github.run_number }}
      registry: "lcacollect"
      name: "project"
  publish-chart:
    uses: lcacollect/.github/.github/workflows/publish-chart.yaml@main
    needs: 
      - test
      - build-container
    with:
      tag: ${{ github.run_number }}
      registry: "lcacollect"
      name: "project"
