name: Container CI/CD Workflow

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage
  workflow_dispatch:

jobs:
  test:
    uses: lcacollect/.github/.github/workflows/test-python.yaml@main
  publish-schema:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-graphql.yaml@main
    needs: test
    with:
      name: 'project'
      branch: ${{ github.ref_name }}
      storage_account: ${{ vars.DEVELOPMENT_STORAGE_ACCOUNT }}
      container_name: ${{ vars.GRAPHQL_CONTAINER_NAME }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
  build-container:
    uses: lcacollect/.github/.github/workflows/build-image.yaml@main
    needs: test
    with:
      tag: "${{ github.run_number }}${{ (github.ref_name != 'main' && '-dev') || ''}}"
      registry: "lcacollect"
      name: 'project'
  publish-chart:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-chart.yaml@main
    needs:
      - test
      - build-container
    with:
      tag: "${{ github.run_number }}${{ (github.ref_name != 'main' && '-dev') || ''}}"
      registry: "lcacollect"
      name: 'project'
  webhook:
    if: github.event_name != 'pull_request'
    needs:
      - publish-schema
      - publish-chart
    uses: lcacollect/.github/.github/workflows/send-dispatch.yaml@main
    with:
      repo_name: 'project'
      receiver_repo: 'lcacollect/router-backend'
    secrets:
      dispatch_token: ${{ secrets.DISPATCH_TOKEN }}
